name: Check cdktf releases

on:
  release:
    types: [published]

jobs:
  check_cdktf_releases:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check for new versions
      run: make check_new_version
